[workspace]

members = [
        "bin/vectrex",
        "bin/vedlitrex",

        "lib/vectrex_core",
        "lib/vectrex_worlds",
        "lib/vectrex_ai",
        "lib/vectrex_net"
    ]


[profile.release]
lto = true
opt-level = 3
debug = false
