
[package]
name = "vemodlatrex"
version = "0.0.0"
authors = ["Chloe Strainge <nullpr.0@gmail.com>"]
edition = "2018"

[dependencies]
vectrex_core = { path = "../../lib/vectrex_core" }

meshopt = "0.1.5"
